name: Sync query.yaml to ReadMe
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.ReadmeIoApiKey }}:6070a8240147d400165ed8af
          oas-file-path: ./query.yaml
