name: Sync inbound.yaml to ReadMe
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.ReadmeIoApiKey }}:606079f404910e006b487151
          oas-file-path: ./inbound.yaml
